name: ext-surp

dependencies:
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - python
  - huggingface::transformers
  - sentencepiece
  - protobuf
  - datasets
  - pandas
  - tqdm
  - pip
  - pip:
    - sball
